In [52]:
import numpy as np
import pandas as pd
import PIL
from PIL import Image
import skimage
import os

In [53]:
os.chdir('D://DKIT//dissertation//Dataset_of_Tomato Leaves//plantvillage//Preprocessed_data//test_data//Bacterial_spot227//')

In [54]:
image = Image.open('BS1.jpg',mode='r')
image = image.convert('RGB')
from skimage import color
grayscale = image.convert('L')
grayscale.show()

In [55]:
x = np.array(grayscale)

In [56]:
print(x)

[[147 148 149 ... 151 151 152]
 [147 147 149 ... 154 154 155]
 [148 148 147 ... 155 155 155]
 ...
 [111 108 109 ... 118 116 113]
 [112 109 110 ... 118 116 113]
 [114 110 111 ... 118 116 113]]


In [58]:
colour = color.gray2rgb(grayscale)
colour.show()

TypeError: 'Image' object is not subscriptable