In [1]:
import numpy as np #importing numpy
import pandas as pd #importing pandas
import PIL #importing pillow for image processing
from PIL import Image#importing image from pillow library
import skimage#importing skimage library
import os#importing os library
import time#importing time library

#Capture start time of the program
start_time = time.time()

In [2]:
from string import digits
#code to remove numbers in a string and assigning it to the variable
r_digits = str.maketrans('', '', digits)
#taking source data folder path to a varible
rawdata_path = 'D://DKIT//dissertation//Dataset_of_Tomato Leaves//plantvillage//Preprocessed_data//Preprocessed_data//'
#changing current librbay to source data
os.chdir(rawdata_path)
#taking sub-directories to a list
dirs = os.listdir()
directories = []
diseases = []
#Taking directories into a list and extract disease name from folder name
for x in dirs:
    res = x.translate(r_digits).lower()
    diseases.append(res)
    temp = rawdata_path + x + '//'
    directories.append(temp)

In [3]:
vector_data = pd.DataFrame(columns=['gray','gray_single','disease'])

In [4]:
x = 0
y=0
gray = []
gray_single = []
disease = []
for i in directories:
    os.chdir(i)
    k = diseases[x]
    pics = os.listdir()
    for j in pics:
        gray_l = []
        image = Image.open(j,mode='r')
        gray_l = image.convert('L')
        gray_l = np.array(gray_l)
        gray.append(gray_l)
        gray_l = gray_l.flatten()
        gray_l = np.array(gray_l)
        gray_single.append(gray_l)
        disease.append(k)
    
    x = x+1

In [5]:
os.chdir('D://DKIT//dissertation//Dataset_of_Tomato Leaves//plantvillage//Preprocessed_data//test_data//')

In [6]:
gray

[array([[147, 148, 149, ..., 151, 151, 152],
        [147, 147, 149, ..., 154, 154, 155],
        [148, 148, 147, ..., 155, 155, 155],
        ...,
        [111, 108, 109, ..., 118, 116, 113],
        [112, 109, 110, ..., 118, 116, 113],
        [114, 110, 111, ..., 118, 116, 113]], dtype=uint8),
 array([[166, 162, 161, ..., 142, 138, 133],
        [167, 165, 166, ..., 142, 141, 139],
        [167, 167, 169, ..., 134, 136, 138],
        ...,
        [169, 162, 157, ..., 130, 130, 131],
        [166, 160, 157, ..., 137, 137, 138],
        [162, 158, 158, ..., 135, 136, 137]], dtype=uint8),
 array([[128, 127, 126, ..., 120, 118, 117],
        [126, 126, 126, ..., 117, 118, 118],
        [126, 126, 128, ..., 113, 115, 118],
        ...,
        [ 85,  93,  89, ...,  51,  54,  57],
        [ 85,  93,  89, ...,  52,  54,  58],
        [ 85,  93,  88, ...,  53,  56,  59]], dtype=uint8),
 array([[116, 118, 118, ..., 111, 114, 118],
        [109, 115, 119, ..., 113, 113, 113],
        [115, 12

In [7]:
df = pd.DataFrame()

In [8]:
gray_df = pd.DataFrame(np.row_stack(gray_single))

In [9]:
gray_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14531 entries, 0 to 14530
Columns: 51529 entries, 0 to 51528
dtypes: uint8(51529)
memory usage: 714.1 MB


In [10]:
gray_df.head()

0      1      2      3      4      5      6      7      8      9      ...  \
0    147    148    149    152    153    152    148    144    144    144  ...   
1    166    162    161    162    159    155    159    168    166    167  ...   
2    128    127    126    125    126    127    129    130    131    130  ...   
3    116    118    118    116    120    128    134    135    126    126  ...   
4    173    170    169    170    173    174    171    167    169    169  ...   

   51519  51520  51521  51522  51523  51524  51525  51526  51527  51528  
0    104    122    118    108    114    112    117    118    116    113  
1    136    129    126    133    133    130    135    135    136    137  
2     58     58     56     58     62     61     56     53     56     59  
3    164    164    166    169    170    169    168    169    169    169  
4    106    108    108    107    105    106    107    117    116    115  

[5 rows x 51529 columns]

In [11]:
disease

['bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_spot',
 'bacterial_

In [12]:
diseases

['bacterial_spot',
 'early_blight',
 'healthy',
 'late_blight',
 'leaf_mold',
 'septoria_leaf_spot',
 'target_spot',
 'tomato_mosaic_virus',
 'tomato_yellow_leaf_curl_virus',
 'two-spotted_spider_mite']